name: "Build XIVLauncher-RB"

on:
  push:
    branches: [RB-patched]
  pull_request:
    branches: [RB-patched]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/XIVLauncher.Core/
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: true
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build
        run: dotnet publish -r linux-x64 --sc --configuration Release --no-restore -o ./dist/XIVLauncher.Core

      - name: Dotnet Test
        run: dotnet test --no-build --verbosity normal
