name: "Release XIVLauncher-RB"

on:
  workflow_dispatch:
  push:
    tags:
      - "rb-v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  Release:
    if: github.repository == 'rankynbass/XIVLauncher.Core'
    runs-on: ubuntu-22.04
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x # Set this to be the same as the projects required dotnet version.

      - name: Dotnet Build
        working-directory: src/XIVLauncher.Core/
        run: |
          dotnet restore
          dotnet publish -r linux-x64 --sc --configuration Release --no-restore -o ./dist/XIVLauncher.Core -p:BuildHash=$(git rev-parse --short HEAD)

      - name: Make tarball
        run: |
          cp CHANGELOG.md README.md LICENSE MIT src/XIVLauncher.Core/dist/XIVLauncher.Core/
          tar -czf XIVLauncher.Core.tar.gz -C src/XIVLauncher.Core/dist/XIVLauncher.Core .
          sha512sum XIVLauncher.Core.tar.gz > XIVLauncher.Core.sha512sum

      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          fail_on_unmatched_files: true
          draft: true
          body_path: RELEASENOTES.md
          files: |
            XIVLauncher.Core.tar.gz
            XIVLauncher.Core.sha512sum
   
